name: ebrain
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # --- LES IMAGES (GIF, PNG) ICI ---
  assets:
    - assets/images/logotournant.gif          # Pour le logo.gif
    - assets/images/games/   # Pour tes composants

  # --- LES POLICES (FICHIERS .TTF) ICI ---
  fonts:
    - family: Rencana
      fonts:
        - asset: fonts/Rencana.ttf